version: "3"
services:
  hub:
    image: selenium/hub
    ports: ["4444:4444"]
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
  chrome:
    image: selenium/node-chrome-debug
    volumes: [/dev/shm:/dev/shm]
    depends_on: [hub]
    ports: ["4501:4505"]
    environment:
      HUB_HOST: hub
  firefox:
    image: selenium/node-firefox-debug
    volumes: [/dev/shm:/dev/shm]
    depends_on: [hub]
    ports: ["4506:4510"]
    environment:
      HUB_HOST: hub
    